spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/practica"
    username: "root"
    password: "2147483647Mpec*"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: create-drop